
FROM python:3.12
# Means we all the things we need to have python in the container

WORKDIR /app

ADD . /app


# Set PYTHONPATH to the app directory
ENV PYTHONPATH=/app


CMD ["python", "-m", "unittest", "tests.test_calculator"]
# The entry command when starting the container, simply runs main file

# After that in terminal you need to build an  image, insert:
# 1.docker build -f <dockerfile_name> -t <image_name>
# 2. docker run <image_name> (if there is no input option)
# docker run -t -i <image_name> (if there is an input option) - i: interactive mode

